#!/usr/bin/python3.6
from os import system as sy
from os import path,chdir
from time import strftime

date = strftime('%d.%m.%y')
murlipath = '/home/anonymous/Documents/Murli/Murli-eng/'
link='http://www.babamurli.com/01.%20Daily%20Murli/02.%20English/02.%20Eng%20Murli%20-%20Pdf/'
if not path.exists(f'{murlipath}Murli-{date}.pdf'):
    chdir(murlipath)
    sy(f'wget {link}{date}-E.pdf')
    sy(f'mv {murlipath}{date}* {murlipath}Murli-{date}.pdf')

sy(f'xdg-open {murlipath}Murli-{date}.pdf')

