#!/home/deepak/anaconda3/bin//python3
import re
from selenium import webdriver
from bs4 import BeautifulSoup  as bs
from requests import get
from sys import argv
from time import sleep

bro = webdriver.Chrome()

nos = re.findall(r'\d+', argv[1])
print(nos)
episodes = []
for no in nos:
	print(no)
	if no in episodes:
		continue

	link = 'http://ww2.chia-anime.tv/naruto-shippuden-episode-{}-english-subbed/'.format(no)
	print(link)
	res = get(link)
	print(res)
	soup = bs(res.content, 'html.parser')
	dlink = soup.find(id = 'download')
	print(dlink, end='\n\n\n')
	if not dlink:
		link = 'http://ww2.chia-anime.tv/naruto-shippuden-{}-english-subbed/'.format(no)
		print(link)
		res = get(link)
		print(res)
		soup = bs(res.content, 'html.parser')
		dlink = soup.find(id = 'download')
		print(dlink,end='\n\n\n')


	episodes.append(re.findall(r'\d+', dlink['title']))
	bro.get(dlink['href'])
	sleep(10)
	bro.find_elements_by_class_name('green')[1].click()

