#!/usr/bin/python3

from datetime import datetime
from os import system as sys
if  5 < int(str(datetime.now().time())[:2]) < 11:
	sys('mpg321 morning.mp3')
elif 11 < int(str(datetime.now().time())[:2]) < 17:
	sys('mpg321 afternoon.mp3')
elif 17 < int(str(datetime.now().time())[:2]) < 21:
	sys('mpg321 evening.mp3') 

elif 21 < int(str(datetime.now().time())[:2]) > 5:
	sys('mpg321 sleep.mp3') 